In [12]:
s = "Hi there Sam!"
s.split()

['Hi', 'there', 'Sam!']

In [13]:
txt = "The diameter of Earth is {diameter}Kilometers"
print(txt.format(diameter = 12742))

The diameter of Earth is 12742Kilometers


In [14]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [16]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all the even integers from 30 to 70")
print(array)

Array of all the even integers from 30 to 70
[20 22 24 26 28 30 32 34]


In [18]:
import numpy as np
x =  np.arange(0,9).reshape(3,3)
print("conacatenated string is",x)

conacatenated string is [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
# Importing Pandas to create DataFrame
import pandas as pd
data = [1,2,3]
# Creating Empty DataFrame and Storing it in variable df
df = pd.DataFrame(data,columns = [''])
  
# Printing Empty DataFrame
print(df)

    
0  1
1  2
2  3


In [22]:
import datetime
import pandas as pd
 
# initializing date
test_date = datetime.datetime.strptime("01-1-2023", "%d-%m-%Y")
 
# initializing K
K = 41
 
date_generated = pd.date_range(test_date, periods=K)
print(date_generated.strftime("%d-%m-%Y"))

Index(['01-01-2023', '02-01-2023', '03-01-2023', '04-01-2023', '05-01-2023',
       '06-01-2023', '07-01-2023', '08-01-2023', '09-01-2023', '10-01-2023',
       '11-01-2023', '12-01-2023', '13-01-2023', '14-01-2023', '15-01-2023',
       '16-01-2023', '17-01-2023', '18-01-2023', '19-01-2023', '20-01-2023',
       '21-01-2023', '22-01-2023', '23-01-2023', '24-01-2023', '25-01-2023',
       '26-01-2023', '27-01-2023', '28-01-2023', '29-01-2023', '30-01-2023',
       '31-01-2023', '01-02-2023', '02-02-2023', '03-02-2023', '04-02-2023',
       '05-02-2023', '06-02-2023', '07-02-2023', '08-02-2023', '09-02-2023',
       '10-02-2023'],
      dtype='object')


In [21]:
import pandas as pd  
      
# List1  
lists = [[1, 'aaa', 22], [2, 'bbb', 25], 
       [3, 'ccc', 24],] 
  
# creating df object with columns specified    
df = pd.DataFrame(lists, columns =[' ', ' ',' ']) 
print(df)

             
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
